### ISSUE TITLE
Explorer: "Open Console Dashboard" shows page with error

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#119]
[kind/bug]

## What versions of software are you using?
- OpenShift version: 3.11

## What did you run exactly?
1. ASSERT: have a cluster that you're logged in to
1. EXEC: in Explorer: pick "Open Console Dashboard" in ctx menu
1. ASSERT: page is opened in browser

## Actual behavior
The page that is opened is showing an error:
![image](https://user-images.githubusercontent.com/25126/68220381-f71e5800-ffe7-11e9-8c0c-c5a1522a9a6d.png)
Hitting the link **console** brings you to the dashboard though.

**Comment by sbouchet** [comment]
error comes from the fact that the remote cluster is using version 3.X, and the method call fails 
because it uses 4.X api. Then the code just adds "/console" to the master URL that is not conform to the actual console URL.
the underlying exception is :
```io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.rh-us-east-1.openshift.com/api/v1/namespaces/openshift-config-managed/configmaps/console-public. Message: Forbidden! User xxxxxxxxxx/api-rh-us-east-1-openshift-com:443 doesn't have permission. configmaps "console-public" is forbidden: User "xxxxxxx" cannot get configmaps in the namespace "openshift-config-managed": no RBAC policy matched.```
(i'm using the same remote cluster as you).

So we should try to get the info from the cluster directly via API ( if it exists ) or try to format the correct url from the master URL. 
Expected : https://console.rh-us-east-1.openshift.com/console
Actual: https://api.rh-us-east-1.openshift.com:443/console

**Comment by jeffmaury** [comment]
The VSCode is suffering the same error, not sure when can hande this user case. Will check how JBoss Tools is handling it

**Comment by jeffmaury** [comment]
JBoss Tools is having the same issue.

**Comment by sbouchet** [comment]
ok. after looking into more, it looks like a lot of the API calls are forbidden for my user account on OpenShift Cluster. I'll try to reach out to the team to find out if they have a solution.

**Comment by sbouchet** [comment]
a workaround found is to simply use the master url, it will automatically forward to the console...
IE : https://api.rh-us-east-1.openshift.com:443
